pagina/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('subida/',include('subida.urls')),
]


urlpatterns += [
    path("",RedirectView.as_view(url='subida/',permanent=True))
]



if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subida/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'Subida'

urlpatterns = [
    path('', views.index, name='index'),
    path('modelos/', views.VistaSubidaModelos.as_view(), name='modelos'),
    path('descarga/<int:ArticuloPk>', views.VistaDescarga.as_view(), name='descarga'),
    path('video/',views.VistaVideo.as_view(),name ='video'),
]

subida/models.py
from django.db import models
from django.contrib.auth.models import User

from django.dispatch import receiver
# Create your models here.
import os
from uuid import uuid4
from pagina.settings import DESCARGA_ROOT
from django.core.files.storage import FileSystemStorage
from stdimage import StdImageField, JPEGField


fs = FileSystemStorage(location=DESCARGA_ROOT)

def wrapper(instance, filename):
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(DESCARGA_ROOT, filename)

def upload_to(instance, filename):
    return 'contenido/user_{0}/{1}'.format(instance.titulo, filename)


#https://docs.djangoproject.com/en/2.2/topics/files/#the-file-object
class Producto(models.Model):
    titulo = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=30)
    imagen = models.FileField(upload_to="almacenamiento/contenido/")
    imagenRedimencionada = StdImageField(upload_to='comprimido',
                                         variations = {'thumbnail': {'width': 224, 'height': 224,"crop": True}},
                                         delete_orphans=True,
                                         default=None)
    descarga = models.FileField(upload_to=upload_to,storage=fs)




class ProductosUser(models.Model):
    perfil = models.FileField(upload_to=upload_to)
    nonbre = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

@receiver(models.signals.post_delete, sender=ProductosUser)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """  path('almacenamiento/', include('almacenamiento.urls')),
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.perfil:
        if os.path.isfile(instance.perfil.path):
            os.remove(instance.perfil.path)


@receiver(models.signals.pre_save, sender=ProductosUser)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file = ProductosUser.objects.get(pk=instance.pk).file
    except ProductosUser.DoesNotExist:
        return False

    new_file = instance.file
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

subida/forms.py
from django import forms
from django.forms import ModelForm
from .models import Producto

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    archivo = forms.FileField()


class FormSubida(ModelForm):
    class Meta:
        model = Producto
        fields = ['titulo','descripcion','imagen','imagenRedimencionada','descarga']

subida/views.py
from django.shortcuts import render

from .forms import UploadFileForm, FormSubida
from .somewhere import handle_uploaded_file
from django.shortcuts import HttpResponse,Http404
from django.views.generic import RedirectView
from .models import Producto,wrapper
import os
def index(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST,request.FILES)
        print()
        if form.is_valid():
            handle_uploaded_file(request.FILES['archivo'].name,request.FILES['archivo'])
            return HttpResponse("que bien")
    elif request.method == 'GET':
        form = UploadFileForm()
        try:
            productos =  Producto.objects.all()
            unProducto = Producto.objects.get(pk=2)
            print(productos)
        except:
            productos = None
            unProducto = None
    return render(request, 'subida/upload.html', {'form': form,
                                                  'productos':productos,
                                                  'unProducto':unProducto})


class VistaSubidaModelos(RedirectView):

    def get(self, request, *args, **kwargs):
        form = FormSubida()
        return render(request, 'subida/uploadmodelo.html', {'form': form})

    def post(self, request, *args, **kwargs):
        print(request.POST,request.FILES)
        form = FormSubida(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponse("Agregado")
        else:
            return render(request, 'subida/uploadmodelo.html', {'form': form})



class VistaDescarga(RedirectView):

    def get(self, request, *args, **kwargs):
        print(kwargs)
        print(request.user)
        try:
            articulo = Producto.objects.get(pk=kwargs['ArticuloPk'])
        except:
            articulo = None

        if articulo is not None:
            path =str(articulo.descarga.storage.location)+"/"+str(articulo.descarga)
            if os.path.exists(path):
                file = open(path,'rb')
                response = HttpResponse(file.read(), content_type='pplication/vnd.ms-excel')
                response['Content-Disposition']='inline; filename='+ os.path.basename(path)
                return response
            raise Http404("errro")
        else:
            raise Http404("error")

    def post(self, request, *args, **kwargs):
        pass

class VistaError(RedirectView):
    def get(self, request, *args, **kwargs):
        return HttpResponse("errooorrrrr")

class VistaVideo(RedirectView):
    def get(self, request, *args, **kwargs):
        return render(request, 'subida/videos.html', {'form':''})

subida/templates/subida/upload.html
{% load static %}

<head>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>
    <script src="{% static 'subida/dropzone/dropzone.js' "></script>

    <link rel="stylesheet" type="text/css" href="{% static 'subida/estilo.css' %}">
</head>

<body>

<div class="card bg-dark">
<div class="card-header text-white text-center">Antiguo</div>
    <div class="card-body text-white">
            <div class="row">
                <div class="col-12 bg-warning">
                    <img class="blah" width="100px">
                </div>
                <div class="col bg-danger">
                     {% for tmp in productos %}

                          <img class="img{{ forloop.counter }}" src="{{tmp.imagenRedimencionada.thumbnail.url}}" onclick="imagen({{ forloop.counter }})">

                     {% endfor %}

                </div>
            <div>
    </div>
</div>

        <script>

           var anterior = 0
            imagen(1);


           function imagen(numero){

                if (anterior == 0)
                {
                var tmpNumero = ".img"+numero;
                $(tmpNumero).css("border-style","solid");
                $(".blah").attr("src",$(tmpNumero).attr('src'));
                anterior = numero;
                }else{
                var tmpNumero = ".img"+numero;
                var anter = ".img"+anterior;
                $(anter).css("border-style","");
                $(tmpNumero).css("border-style","solid");
                $(".blah").attr("src",$(tmpNumero).attr('src'));
                anterior = numero;
                }
           }

        </script>

        {% comment "fff" %}
<div class="card">
    <div class="card-header">Antiguo2</div>
    <div class="card-body">
        {% if productos %}
            {% for tmp in productos %}
            <p>{{tmp.titulo}}</p>
            <p> {{tmp.descripcion}}</p>

        <img src="{{tmp.imagenRedimencionada.thumbnail.url}}">
        <img src="{{tmp.imagen.url}}">
        <h2>Descargas</h2>
        <a href="{% url 'Subida:descarga' tmp.pk%}">Descarga</a>

        <video src="{{tmp.imagen.url}}" autoplay poster="{{tmp.imagenRedimencionada.thumbnail.url}}">
          Tu navegador no admite el elemento <code>video</code>.
        </video>

        {% endfor %}
        {% else %}
        <p>no hay</p>
        {% endif %}

    </div>
</div>


        {% endcomment %}






</body>

subida/templates/subida/uploadmodelo.html
{% load static %}

<html>
<title>modelos</title>
<head>

    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'subida/estilo.css' %}">



    <link rel="stylesheet" type="text/css" href="{% static 'subida/tagss/tagger.css' %}">
    <script src="{% static 'subida/tagss/tagger.js' %}"></script>

</head>

<body>
<div class="container">
    <div class="row">

        <div class="col mt-3">
            <div class="card">
                <div class="card-body">

            <form action="#" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                <input type="text" value="" name="tags" />
                <input type="submit">
            </form>
                


            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">25%</div >
                </div>
                <div id="status"></div>
                </div>
            </div>
            </div>
        </div>
    </div>
</body>

<script>

var t1 = tagger(document.querySelector('[name="tags"]'), {
    allow_duplicates: false,
    allow_spaces: true,
    completion: {list: ['foo', 'bar', 'baz']}
  });




$(function() {

    var bar = $('.progress-bar');
//    var percent = $('.percent');
    var status = $('#status');

    $('form').ajaxForm({
        beforeSend: function() {
            status.empty();
            var percentVal = '0%';
            bar.width(percentVal);
            bar.html(percentVal);
            //percent.html(percentVal);
        },
        uploadProgress: function(event, position, total, percentComplete) {
            var percentVal = percentComplete + '%';
            bar.width(percentVal);
            bar.html(percentVal);
         //   percent.html(percentVal);
        },
        complete: function(xhr) {
            status.html(xhr.responseText);
        }
    });
});



</script>

</html>

subida/templates/subida/videos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />

  <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
  <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'subida/estilo.css' %}">
</head>

<body>

<a href="/ArchivosMedia/almacenamiento/contenido/233.mp4"> Descarga </a>

  <video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="640"
    height="264"
    data-setup="{}"
  >

    <source src="http://localhost:8080/subida/descarga/10" type="video/mp4" />
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a
      web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank"
        >supports HTML5 video</a
      >
    </p>
  </video>

  <script src="https://vjs.zencdn.net/7.8.4/video.js"></script>
</body>




</html>